version: 2

models:
  - name: airplane_type_dim
    constraints:
      - type: primary_key
        columns: type_id
    columns:
      - name: type_id
        data_type: int
      - name: identifier
        data_type: varchar(50)
      - name: description
        data_type: text

  - name: airplane_dim
    constraints:
      - type: primary_key
        columns: airplane_id
    columns:
      - name: airplane_id
        data_type: int
      - name: capacity
        data_type: int
        constraints:
          - type: not_null
      - name: type_id
        data_type: int
        constraints:
          - type: not_null
          - type: unique
          - type: foreign_key
            expression: public_bi.airplane_type_dim (type_id)
    
  - name: airport_dim
    constraints:
      - type: primary_key
        columns: airport_id
    columns:
      - name: airport_id
        data_type: int
      - name: iata
        data_type: char(3)
      - name: icao
        data_type: char(3)
        constraints:
          - type: not_null
      - name: name
        data_type: varchar(50)
        constraints:
          - type: not_null
      - name: city
        data_type: varchar(50)
      - name: country
        data_type: varchar(50)
      - name: latitude
        data_type: decimal(11,8)
        constraints:
          - type: not_null
      - name: longitude
        data_type: decimal(11,8)
        constraints:
          - type: not_null
      - name: geolocation
        data_type: point
        constraints:
          - type: not_null