version: 2

models:
  - name: airplane_type_dim
    columns:
      - name: type_id
        description: "Unique identifier for the airplane type"
        tests:
          - unique
        meta:
          dbt_type: int
      - name: identifier
        description: "Identifier for the airplane type"
        tests:
          - unique
        meta:
          dbt_type: string
      - name: description
        description: "Description of the airplane type"
        meta:
          dbt_type: string

  - name: airplane_dim
    columns:
      - name: airplane_id
        description: "Identifier for the airplane"
        tests:
          - unique
        meta:
          dbt_type: int
      - name: capacity
        description: "Description of the airplane capacity"
        meta:
          dbt_type: int
      - name: type_id
        description: "Description of the airplane type"
        meta:
          dbt_type: int
        tests:
          - not_null
          - foreign_key:
            to: "{{ ref('airplane_type_dim') }}.type_id"
      